"""create ingestion failures table

Revision ID: c5a2dbc094c3
Revises: d5087e9df784
Create Date: 2026-08-10 17:19:13.865062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5a2dbc094c3'
down_revision: Union[str, Sequence[str], None] = 'd5087e9df784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('error_type', sa.String(length=200), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_failures_external_id'), 'ingestion_failures', ['external_id'], unique=False)
    op.create_index(op.f('ix_ingestion_failures_failed_at'), 'ingestion_failures', ['failed_at'], unique=False)
    op.create_index(op.f('ix_ingestion_failures_source'), 'ingestion_failures', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_failures_source'), table_name='ingestion_failures')
    op.drop_index(op.f('ix_ingestion_failures_failed_at'), table_name='ingestion_failures')
    op.drop_index(op.f('ix_ingestion_failures_external_id'), table_name='ingestion_failures')
    op.drop_table('ingestion_failures')
    # ### end Alembic commands ###
