"""create weather alerts table

Revision ID: d5087e9df784
Revises: 3dc9b547cf71
Create Date: 2026-08-09 23:02:33.267384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5087e9df784'
down_revision: Union[str, Sequence[str], None] = '3dc9b547cf71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=500), nullable=False),
    sa.Column('event', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('certainty', sa.String(length=50), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('area_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('response', sa.String(length=100), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', name='uq_weather_alerts_alert_id')
    )
    op.create_index(op.f('ix_weather_alerts_effective_at'), 'weather_alerts', ['effective_at'], unique=False)
    op.create_index(op.f('ix_weather_alerts_event'), 'weather_alerts', ['event'], unique=False)
    op.create_index(op.f('ix_weather_alerts_expires_at'), 'weather_alerts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_weather_alerts_status'), 'weather_alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_alerts_status'), table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_expires_at'), table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_event'), table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_effective_at'), table_name='weather_alerts')
    op.drop_table('weather_alerts')
    # ### end Alembic commands ###
